### ISSUE TITLE
Database permission upon creation

### ISSUE THREAD

**Issue by triandco** [verida/datastore#10]
# Summary
I have been writing a little prototype to test Verida database permission settings, I noticed that I couldn't set the permission of the new database to be anything but  { read: "owner", write: "owner"}. 

# Reproduction
1. Connect to Verida app using either Ethereum or NEAR
2. Open a database with a brand new name with the permission ```{ read: "public", write: "owner"}```

# Expect
A new database is created with the specified permission

# Actual
New database is returned with permissions props set to ```{ read:"owner", write: "owner"}```

# Preliminary investigation
I tracked it down to [database.js](https://github.com/verida/datastore/blob/ab6bfe57a19bd1c6794cee0caa179be3b8ab0964/src/database.js#L38) where the permission is currently being overridden:
```javascript
this.permissions = _.merge({
            read: "owner",
            write: "owner",
            readList: [],
            writeList: []
        }, this.config.permissions ? this.config.permissions : {});
```
Since [lodash merge](https://lodash.com/docs/4.17.15#merge) would not override props that already exists, this means the read and write permission of a database would always be the owner. 

# Side note
I was thinking about getting around this by setting the permission again. I noticed there's a way to update the set of users for read-list and write-list with [Database.updateUsers](https://github.com/verida/datastore/blob/ab6bfe57a19bd1c6794cee0caa179be3b8ab0964/src/database.js#L308), but I couldn't find the one that does it at the "owner"/"public"/"users" level

**Comment by tahpot** [comment]
>Open a database with a brand new name with the permission { read: "public", write: "owner"}

What's the actual code you're running to create the database?

**Comment by triandco** [comment]
Oh yes! sorry I forgot to add the code repo 😅. [Here it is](https://github.com/triandco/verida-messaging-prototype/tree/feat/database-permission/src). 

And this is the specific [file](https://github.com/triandco/verida-messaging-prototype/blob/feat/database-permission/src/DatabasePermissionApp.svelte). Below is the excerpt.
```typescript
// let dbName="somename"; let app = new Verida({*}); await app.connect etc...

const permissions = {
    read: 'public',
    write: 'owner'
}; 
async function createDatabase(){
  db = await app.openDatabase(dbName, app.user.did, {
    permissions: permissions
  });
 console.log(db.permissions);// {read:'owner',write:'owner'} 
}

```

**Comment by tahpot** [comment]
Thanks!

Sorry, the documentation was outdated, but has now been [updated](https://github.com/verida/datastore/commit/d556c05fb3e7a988c269bdc216bcf1a226d540b0).

Don't pass the `app.user.did` parameter, ie:

```
db = await app.openDatabase(dbName, {
    permissions: permissions
  });
```

The `did` for the second parameter is only required when calling `app.openExternalDatabase(dbName, did, config)`.

**Comment by triandco** [comment]
Excellent! It works. Thank you! 🙏
