### ISSUE TITLE
Datastore initialisation failed in non-browser environment

### ISSUE THREAD

**Issue by triandco** [verida/datastore#15]
Datastore is not working on the server due to window object being undefined.

# Reproduction
1. Create a node app 
2. Install ```@verida/datastore```  0.7.3
3. Initialise verida in index.js  using server method
```javascript
const chain = 'ethr'
const address = '{some address}'
const privateKey = '{some private key}`

const app = new Verida({
  chain: chain,
  address: address,
  privateKey: privateKey
})
```

4. Run node app with ```node index.js```

# Expectation
Initialise successfully

# Actual
Encounter error:
```
if (!window.nearAPI) window.nearAPI = nearAPI;
^
ReferenceError: window is not defined
 at Object.<anonymous> (.\node_modules\@verida\datastore\lib\helpers\near.js:18:1)
```

Please see the [example github repository](https://github.com/triandco/verida-server-app) for more details.

**Comment by tahpot** [comment]
@triandco This appears to be a recently introduced bug with the addition of NEAR support not checking the environment.

Will apply a fix for you by tomorrow.

**Comment by triandco** [comment]
On a related now, my build is giving problem with this particular line:

https://github.com/verida/datastore/blob/18ffc7ef52eedebfc9731da3c7c47fbeda94c52f/src/databases/public.js#L36

I think we might want to put a ```const``` before it.

**Comment by tahpot** [comment]
This should be fixed with: https://github.com/verida/datastore/commit/b2ac292a2c69cb53100b536a4e4be43645970db5

I haven't created a new release just yet, just in case you hit any other new issues running in NodeJs.

You should be able to use `npm link` to use this version:

```
git clone https://github.com/verida/datastore
cd datastore
npm install
npm run build
npm link
cd ../verida-server-app (?)
npm link @verida/datastore
node index.js
```

If you don't hit any other issues, I'll create a proper 0.7.4 release so you can install properly via npm.

**Comment by triandco** [comment]
Hi @tahpot, we haven't hit any issues since. Would you be able to create a new release for this, please?

Thank you

**Comment by tahpot** [comment]
@triandco Done.

https://www.npmjs.com/package/@verida/datastore/v/0.7.4

**Comment by triandco** [comment]
Thank you very much @tahpot! 👍
