### ISSUE TITLE
Unable to send messages with error: Invalid private key format. Expecting 32 bytes, but got 64

### ISSUE THREAD

**Issue by triandco** [verida/datastore#9]
# Summary
Following [Verida messaging documentation](https://docs.datastore.verida.io/#/messaging), I was trying to send a message between two users in the same application using NEAR as the provider when I encountered this error.

# Reproduction
1. Create a Verida app using NEAR protocol.
1. Sign in using two different NEAR account in different browsers
1. Attempt to send a message using app.outbox.send()

You can clone and run the prototype in [this repository](https://github.com/triandco/verida-messaging-prototype) to replicate the issue.

# Expected
Message sent

# Actual
Message not sent. Received error message in console:
```
Uncaught (in promise) Error: Invalid private key format. Expecting 32 bytes, but got 64
    at W (index.js:1)
    at Object.exports.SimpleSigner (index.js:1)
    at Outbox._callee$ (outbox.js:148)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (outbox.js:24)
    at _next (outbox.js:26)
```

**Comment by tahpot** [comment]
This turned out to be an issue with the `did-jwt` dependency which had bumped a version breaking the signature generation for encrypted messages.

I've updated this dependency and updated the datastore library to correctly use this updated version.

Upgrade to `@verida/datastore@0.7.3` and this should now be fixed.

**Comment by tahpot** [comment]
As an aside, I suggest you avoid using NEAR DID's in the browser at the moment and stick with Ethereum.

If you clear your browser cache and then re-authenticate through the NEAR web wallet, you will be given a brand new private key, which will break all your encrypted databases.

The QR code sign in supported by the Verida Vault will avoid this issue as it will always return the same private key for every authentication request.

**Comment by triandco** [comment]
Thank @tahpot. I upgraded to the new 0.7.3 and it is working now. 👍
